### PR TITLE
Merge branch 111122 --> Main

### PR DESCRIPTION
**Pull request by JosteinEng**
### **Update main**
**Branch merge:**
- _Daniel-Branch
- Jostein-Branch
- Michael-Branch
- Hassan-Branch
- Frida-Branch
- HC-Branch_

### CODE REVIEW

**Comment by MichaelTangeraas** [comment]
Looks good

**Review by MichaelTangeraas — APPROVED** [review]
Looks good

**Review by Blathee — APPROVED** [review]
Looks great!!!

**Comment by JosteinEng** [comment]
Yeey!

**Pull request merged**
